export const REACT_APP_SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL;
export const REACT_APP_SUPABASE_KEY = process.env.REACT_APP_SUPABASE_KEY;

export default {
  REACT_APP_SUPABASE_KEY,
  REACT_APP_SUPABASE_URL,
};
